version: '3.9'

services:
  web:
    image: node:20-alpine
    container_name: spo-website-dev
    working_dir: /app
    ports:
      - '3000:3000' # Next.js
      - '4001:4001' # TinaCMS
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: sh -c "yarn install && yarn dev"
    restart: unless-stopped
    stdin_open: true
    tty: true
